version: 1.0.{build}
environment:
  nodejs_version: "5.1.1"
  # postgres
  POSTGRES_PORT: tcp://localhost:5432
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_DB: sqlectron
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.4
  PGUSER: postgres
  PGPASSWORD: Password12!
  # mysql
  MYSQL_PORT: tcp://localhost:3306
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  MYSQL_ENV_MYSQL_DATABASE: sqlectron
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.6
  MYSQL_PWD: Password12!
services:
  - mysql
  - postgresql94
init:
- ps: Install-Product node $env:nodejs_version
- npm -v
- node -v
- npm cache clean
- SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%
test: false
install:
- npm install
build_script:
# postgres
- createdb sqlectron
- psql -d sqlectron -a -f spec/databases/postgresql/schema/schema.sql
# mysql
- mysql -e "drop database test; create database sqlectron;" --user=root
- mysql sqlectron < spec/databases/mysql/schema/schema.sql --user=root
- npm test
